### ISSUE TITLE
mean , std dimensions do not match

### ISSUE THREAD

**Issue by jmwang0117** [astra-vision/FAMix#2]
Thank you for your great work!

When I was doing the "Training" step, an error occurred on line 42 in utils.py, indicating that the dimensions did not match. Displayed as follows:

![微信截图_20240420034637](https://github.com/astra-vision/FAMix/assets/51500826/18d82210-2abc-4beb-9a49-19e8d6e44356)

how to solve this problem? 

Additionally, line 13 in patch_PIN.py should be modified to: from utils.freeze import freeze_all

**Comment by mfahes** [comment]
Thanks for your comments. Indeed the batch size was hard-coded in utils.py. It seems you're using a batch size of 12. This has been fixed.

"Additionally, line 13 in patch_PIN.py should be modified to: from utils.freeze import freeze_all". That's right, Thanks!

**Comment by mfahes** [comment]
I'm closing this issue. Please feel free to re-open it if you have additional comments.
