### ISSUE TITLE
Pre-trained models? 

### ISSUE THREAD

**Issue by donglao** [astra-vision/FAMix#3]
Hi,

Thanks for sharing your amazing work. Are you planning to release your trained weights? I am particularly interested in R50DeepLabV3+

Thanks

**Comment by mfahes** [comment]
Hi,

Thank you for your interest in the work. You can download the weights here: https://drive.google.com/drive/folders/1GzajnYyDCUL7Xl0zjjU7_n73ucuyU5SS?usp=sharing
