### ISSUE TITLE
RuntimeError: "im2col_out_cpu" not implemented for 'Long'

### ISSUE THREAD

**Issue by jxthyatt** [astra-vision/FAMix#6]
Thank you for excellent job!

When I run python3 patch_PIN.py with --dataset gta5, it works.
However, when I run python3 patch_PIN.py with --dataset cityscapes, it fails to work. (My environment is Python=3.8.18, torch=1.8.1+cu111)

Dataset: cityscapes, Train set: 2649, Val set: 326
i =  0
Traceback (most recent call last):
  File "patch_PIN.py", line 344, in <module>
    main(random_styles=random_styles)
  File "patch_PIN.py", line 247, in main
    lbl_patches = unfold(labels_, kernel_size=256, stride=256).permute(-1,0,1).reshape(-1,1,256,256) ## (div*div*B,1,H/div,W/div)
  File "/mnt/home/jxt/miniconda3/envs/FAMix/lib/python3.8/site-packages/torch/nn/functional.py", line 4313, in unfold
    return torch._C._nn.im2col(input, _pair(kernel_size), _pair(dilation), _pair(padding), _pair(stride))
RuntimeError: "im2col_out_cpu" not implemented for 'Long'

**Comment by mfahes** [comment]
Hi, this has been fixed [2f1ef9d](https://github.com/astra-vision/FAMix/commit/2f1ef9de24a29590113dc0c212704709f8bf2f15).
